{
    parserClass="lu.ewen.minijvm.language.parser.MiniJvmParser"

    psiClassPrefix="MiniJvm"
    psiImplClassSuffix="Impl"
    psiPackage="lu.ewen.minijvm.language.psi"
    psiImplPackage="lu.ewen.minijvm.language.psi.impl"

    elementTypeHolderClass="lu.ewen.minijvm.language.psi.MiniJvmTypes"
    elementTypeClass="lu.ewen.minijvm.language.psi.MiniJvmElementType"
    tokenTypeClass="lu.ewen.minijvm.language.psi.MiniJvmTokenType"
}

miniJvmFile ::= item_*

private item_ ::= (LABEL|EXPRESSION|COMMENT|EOL_WS)

// Just to define the symbols
also ::= (LINE_WS|EOL_WS)